from enum import Enum


class UserRole(str, Enum):
    SUPER_ADMIN = "SUPER_ADMIN"
    RECEPTIONIST = "RECEPTIONIST"
    ENQUIRY_OFFICER = "ENQUIRY_OFFICER"
    COUNSELLOR = "COUNSELLOR"
    ADMISSION_OFFICER = "ADMISSION_OFFICER"
    ENROLLMENT_OFFICER = "ENROLLMENT_OFFICER"
    VISA_OFFICER = "VISA_OFFICER"
    STUDENT = "STUDENT"